ERRO-20200201_100405_956-2020-02-01 10:04:05,956  send_data_to_cas.py   CAS接続失敗しました。再接続1次起動中...
ERRO-20200201_100411_587-2020-02-01 10:04:11,587  send_data_to_cas.py   CAS接続失敗しました。再接続2次起動中...
FATAL-20160203_100417_298-send_data_to_cas.py : FATAL  CAS接続できません。入力データCAS送信処理が異状終了しました。
